#
# Makefile for AC83xx BackCar communication Driver
# 

obj-m += auxdetect.o

ccflags-y += -I$(srctree)/drivers/misc/atc/libosal/inc/
ccflags-y += -I$(srctree)/drivers/misc/atc/inc/
ccflags-y += -I$(srctree)/include/media/atc/
ccflags-y += -I$(srctree)/arch/arm/mach-ac83xx/include/mach/
